# pastiin direktori ada di turu_backend
# cd turu_backend

# dart pub get
# dart run bin/server.dart


name: turu_backend
description: Backend login/register untuk Flutter dengan Aiven MySQL
version: 1.0.0

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.4
  mysql_client: ^0.0.27
  bcrypt: ^1.1.3
  dotenv: ^4.0.1
  path: ^1.8.0
  shelf_cors_headers: ^0.1.5